/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AtVideo {
    }
}
declare global {
    interface HTMLAtVideoElement extends Components.AtVideo, HTMLStencilElement {
    }
    var HTMLAtVideoElement: {
        prototype: HTMLAtVideoElement;
        new (): HTMLAtVideoElement;
    };
    interface HTMLElementTagNameMap {
        "at-video": HTMLAtVideoElement;
    }
}
declare namespace LocalJSX {
    interface AtVideo {
    }
    interface IntrinsicElements {
        "at-video": AtVideo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "at-video": LocalJSX.AtVideo & JSXBase.HTMLAttributes<HTMLAtVideoElement>;
        }
    }
}
